config/routes.rb
Cartogenesis::Application.routes.draw do

  root to: 'welcome#index'

  resources :user
  get '/signin', to: 'user#new_session', as: 'signin'
  post '/sessions', to: 'user#create_session', as: 'sessions'
  delete '/sign_out', to: 'user#destroy_session', as: 'signout'

  get '/games/:id/start', to: "games#start_game", as: 'start_game'

  patch '/games/:id/leave', to: "games#leave_game", as: 'leave_game'

  get '/game_portal/:id', to: 'games#portal'

  get '/turn_logs/:id', to: 'turn_logs#return_json'

  post '/landmark/', to: 'landmarks#create', as: 'create_landmark'

  resources :games do
    resources :chronicles do
      resources :turn_logs do
      end
    end
  end

  # get '/test3d', to: 'games#test3d'

  resources :games

  resources :board, only: [ :update , :show, :create]

  get '/create_board', to: 'board#create'

  get '/join/:game_slug', to: 'games#join_game'

  get '/play/:game_slug', to: "games#play_game", as: 'play_game'

  post '/players/:game_slug', to: "players#create", as: 'players'

  get '/tutorial', to: "tutorial#show", as: 'tutorial'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :tiles
  has_one :board
  has_many :players
  has_many :users, through: :players
  has_many :ages
  has_many :turn_logs
  has_one :chronicle
  before_create :generate_url

  def in_game?(user)
    users.include?(user)
  end

  def generate_url
    lowercase_letters = ('a'..'z').to_a
    uppercase_letters = lowercase_letters.map(&:upcase)
    numbers = (0..9).to_a
    char_set = lowercase_letters + uppercase_letters + numbers
    self.slug = char_set.sample(8).join()
  end

  def assign_round_points
    self.players.each do |player|
      player.points = player.points + (rand(6) +rand(6) + 2)
      player.save
    end
  end

  def end_turn
    self.turn_counter = self.turn_counter + 1
    if self.turn_counter > self.players.length
        new_round
    end
    next_player
  end

  def next_player
    self.active_player = self.players.order(id: :asc)[self.turn_counter - 1].id
  end

  def new_round
    self.round_counter = self.round_counter + 1
    self.update(turn_counter: 1)
    self.next_player
    assign_round_points
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new()
  end

  def portal
    @game = Game.find(params[:id])
    render :create
  end

  def index
  end

  def test3d

    render :test_index
  end

  def create
    @game = Game.create()
    board = Board.create(board_size: 7, game_id: @game.id)
    @game.board = board
    data = []
    json_params.each do |string|
      data.push(JSON.parse(string.to_json))
    end
    data.each do |datum|
      board.tiles << Tile.create(coordinates: datum['coordinates'], terrain: datum['terrain'], radius: datum['radius'])
    end
    @tiles = board.tiles.order(id: :asc)
    @game.update(chronicle: Chronicle.create(initial_board_json: JSON.parse(board.tiles.to_json)))
    render json: @game
  end

  def update
    @game = Game.find(params[:id])
    @board = Board.find_by(game_id: params[:id])
    points = params[:points][:to_s]
    player = Player.find(@game.active_player)
    player.points = points
    player.save
    @game.end_turn
    @game.save
    WebsocketRails[@game.slug.to_sym].trigger(:end_turn, {board_json: @tiles, myTurn: true})
    redirect_to play_game_path(@game.slug)
  end

  def join_game
    @game = Game.find_by(slug: join_game_params)
  end

  def leave_game
    @game = Game.find(params[:id])
    player = Player.where(game_id: @game.id, user_id: current_user.id)
    @game.players.delete(player)
    redirect_to root_path
  end

  def start_game
    @game = Game.find(params[:id].to_i)
    @game.active_player = @game.players[0].id
    @game.assign_round_points
    @game.save
    redirect_to play_game_path(@game.slug)
  end

  def play_game
    @game = Game.find_by(slug: params[:game_slug])
    @players = @game.players.order(id: :asc)
    @points = Player.find(@game.active_player).points
  end

  def end_turn
    @game = Game.find_by(slug: params[:game_slug])
    @players = @game.players.order(id: :asc)
    @points = Player.find(@game.active_player).points
    render partial: 'side_panel'
  end

  def json_params
    params.require(:_json)
  end

  def join_game_params
    params.require(:game_slug)
  end
end

app/views/games/create.html.erb
<h1>Game Lobby</h1>
  <form action=<%="/games/#{@game.id}/start"%> method='post'>
    <input name="_method" type="hidden" value="PATCH">
    <input name="authenticity_token" type="hidden" value="#{authenticity_token}">
    <ul id='player_list'>
    <li><input type="text" name="players[]" placeholder="Player Name"></li>
    </ul>
    <button class="add_player" type="button">Add Player</button>
    <input type="submit" value="Enter World">
  </form>

app/views/games/join_game.html.erb
<p>Share the URL to invite your friends to join!</p>
<%= form_for :player, url: players_path(@game.slug), html: {id: 'join_game'} do |f| %>
  <p>
    <%= hidden_field_tag :game_id, @game.id %>
    <%= f.label :name, "And Lo!" %>
    <%= f.text_field :name, placeholder: "Deity Name"%>
    discovered existence, and as they existed so existed the world.
  </p>
    <%= f.submit 'Join Game', id: "join_game" %>
<%end%>

app/views/games/new.html.haml
#create_game_page
  %div{:id => 'slider'}

  .game_container

    .create_board_svg_container
      #toolbar
      = form_tag games_path, id: "accept_board", method: :post do
        = submit_tag "Accept Map and Create Game", id: "accept_map_button", class: "hidden_accept"
      %button.generate_map{type: "button", id: 'generate_map'} Generate Map
      .games.new
:javascript
  $(document).ready( function() {
    $('#generate_map').on("click", function(){
      if($('#accept_map_button').hasClass('hidden_accept')) {
        console.log("HELLO!")
        $('#accept_map_button').removeClass('hidden_accept');
      }
    });
  });

app/views/games/old_create.html.haml
%h1 Game Lobby
%form{ action: "/games/#{@game.id}", id:'players', method: :post}
  %input{ name: "_method", type: "hidden", value: "PATCH"}
  %input{ name: "players[]", placeholder: "Player Name"}/
  %button.add_player{type: "button", id: 'add_player'} Add Player
  %input{type: "submit", value: "submit"}/

app/views/games/play_game.html.haml
#game_page
  #landmark_modal
    .header
      %h3 Raise a Landmark
    %form{action: '/landmark/', method: 'POST', id: 'create_landmark'}
    .txt
      %label{for: "Name"} Landmark Name:
      %input#landmark_name{name: "", type: "text"}
    .txt
      %label{for: "description"} Description:
      %input#landmark_description{name: "", type: "text"}
    .tile_info_field
      %input#tile_info{ type: "hidden" }
    .btn.clearfix
      %a.close{href: "#"} Mark the Land!
      %a.close.cancel{href: "#"} Cancel
  #left_panel_wrapper
    #left_panel_top
      .tabs#tabs_top
        .tab
          %input#tab-1{name: "tab-group-1", type: "radio", checked: "checked"}
          %label{for: "tab-1"} Game
          .content
            #round
              #current_round
                %p
                  Round #{@game.round_counter}, active player:
                  %br
                  #{Player.find(@game.active_player).name}
            #points
              %p
                Players and Points:
              %ul
                -@game.players.each do |player|
                  %li
                    #{player.name}:
                    %span.points
                      =player.points
            - if Player.find_by(id: @game.active_player, user_id: current_user.id)
              #history_input
                %p
                  = text_area_tag(:turn_log_documentation, nil, placeholder: "#{Player.find(@game.active_player).name} stirred, and as they breathed, they did some stuff.  Record your history here!")
                  = form_tag @game, class: "end_turn", method: :patch do |f|
                    = hidden_field(:points, :to_s)
                    = submit_tag "End Turn"
                    #leave_game_button
                      = button_to("Leave Game", leave_game_path(@game.id), method: :patch)
        .tab
          %input#tab-2{name: "tab-group-1", type: "radio"}
          %label{for: "tab-2"} History
          .content
            #chronicle
              %ul
                - @game.chronicle.turn_logs.each do |turn_log|
                  %li
                    %p
                      = turn_log.active_player.name.upcase + "'s reign:"
                    %p
                      = link_to  'the world as it was', game_chronicle_turn_log_path(@game, @game.chronicle, turn_log), target: "_blank"
                    %p
                      = turn_log.documentation
    #left_panel_middle
      - if Player.find_by(id: @game.active_player, user_id: current_user.id)
        .tabs#tabs_middle
          .tab
            %input#tab-4{name: "tab-group-2", type: "radio", checked: "checked"}
            %label{for: "tab-4"} Land
            .content
              #toolbar
          .tab
            %input#tab-5{name: "tab-group-2", type: "radio"}
            %label{for: "tab-5"} Landmarks
            .content
              #landmark_panel
      - else
        #wait_panel
          %p
            Waiting for #{Player.find(@game.active_player).name} to finish. Check out the logs on the history tab while you wait!
    #left_panel_bottom
      - if signed_in?
        %p
          Chat:
        #chat_window
        %form.chat_form{action: "#", method: "get"}
          %textarea#chat_input{cols: "30", rows: "5"}
          %br
          %input{type: "submit", value: "Send"}
      - else
        %p You must sign in to see chat!


  .play_game_svg_container
    .games.play{id: @game.id}
  .chronicle_id_container{id: @game.chronicle.id}

app/views/games/test_index.html.erb
<html>
  <head>
    <style>canvas { width: 100%; height: 100%; }</style>

  </head>
  <body>
    <div id='3d'></div>
  </body>
</html>