config/routes.rb
Cartogenesis::Application.routes.draw do

  root to: 'welcome#index'

  resources :user
  get '/signin', to: 'user#new_session', as: 'signin'
  post '/sessions', to: 'user#create_session', as: 'sessions'
  delete '/sign_out', to: 'user#destroy_session', as: 'signout'

  get '/games/:id/start', to: "games#start_game", as: 'start_game'

  patch '/games/:id/leave', to: "games#leave_game", as: 'leave_game'

  get '/game_portal/:id', to: 'games#portal'

  get '/turn_logs/:id', to: 'turn_logs#return_json'

  post '/landmark/', to: 'landmarks#create', as: 'create_landmark'

  resources :games do
    resources :chronicles do
      resources :turn_logs do
      end
    end
  end

  # get '/test3d', to: 'games#test3d'

  resources :games

  resources :board, only: [ :update , :show, :create]

  get '/create_board', to: 'board#create'

  get '/join/:game_slug', to: 'games#join_game'

  get '/play/:game_slug', to: "games#play_game", as: 'play_game'

  post '/players/:game_slug', to: "players#create", as: 'players'

  get '/tutorial', to: "tutorial#show", as: 'tutorial'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :password, length: { minimum: 6 }
  validates :username, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_many :players
  has_many :games, through: :players

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to new_game_path
    else
      render 'new'
    end
  end

  def new_session
  end

  def create_session
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in @user
      redirect_to new_game_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy_session
    sign_out
    redirect_to new_user_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/views/user/new.html.haml
.title
  %h1 CartoGenesis
  #sign_up_sign_in
    #signin.front_buttons.hide
      - if signed_in?
        %p
          = link_to "NEW GAME", new_game_path, method: "get"
      - else
        %p
          SIGN IN
        = form_for :session, url: sessions_path do |f|
          .form_inputs
          = f.label :email
          .form_inputs
          = f.text_field :email
          .form_inputs
          = f.label :password
          .form_inputs
          = f.password_field :password
          .form_inputs
          = f.submit "Sign in", class: "login_button"
    #signup.front_buttons.hide
      - if signed_in?
        %p
          = link_to "SIGN OUT", signout_path, method: "delete"
      - else
        %p
          SIGN UP
        = form_for :user, url: user_index_path, method: :post do |f|
          %p
          = f.label :username
          %p
          = f.text_field :username
          %p
          = f.label :email
          %p
          = f.text_field :email
          %p
          = f.label :password
          %p
          = f.password_field :password
          %p
          = f.label :password_confirmation, "Confirmation"
          %p
          = f.password_field :password_confirmation
          %p
          = f.submit "Create an account", class: "signup_button"
  - flash.each do |key, value|
    .alert.alert-error
      %div{class: "alert alert-#{key}"}= value
  - unless @user.nil?
    - if @user.errors.any?
      #error_explanation
        .alert.alert-error
          The form contains #{pluralize(@user.errors.count, "error")}.
          %ul
            - @user.errors.full_messages.each do |msg|
              %li
                * #{msg}
:javascript
  $(document).ready( function() {
    $('#signin p').on("click", function(){
      if($(this).parent().hasClass('hide') && $(this).children('a').text() != "NEW GAME") {
        console.log(this);
        if($('#signup').hasClass('front_buttons_open')) {
          $('#signup').animate({height:130},200).addClass('hide').removeClass('front_buttons_open');
        }
        $(this).parent().animate({height:540},200).removeClass('hide').addClass('front_buttons_open');
      } else {
        $(this).parent().animate({height:130},200).addClass('hide').removeClass('front_buttons_open');
      }
    });
  $('#signup p').on("click", function(){
    if($(this).parent().hasClass('hide') && $(this).children('a').text() != "SIGN OUT") {
      if($('#signin').hasClass('front_buttons_open')) {
        $('#signin').animate({height:130},200).addClass('hide').removeClass('front_buttons_open');
      }
      $(this).parent().animate({height:800},200).removeClass('hide').addClass('front_buttons_open');
    } else {
      $(this).parent().animate({height:130},200).addClass('hide').removeClass('front_buttons_open');
    }
  });
  } );