config/routes.rb
Cartogenesis::Application.routes.draw do

  root to: 'welcome#index'

  resources :user
  get '/signin', to: 'user#new_session', as: 'signin'
  post '/sessions', to: 'user#create_session', as: 'sessions'
  delete '/sign_out', to: 'user#destroy_session', as: 'signout'

  get '/games/:id/start', to: "games#start_game", as: 'start_game'

  patch '/games/:id/leave', to: "games#leave_game", as: 'leave_game'

  get '/game_portal/:id', to: 'games#portal'

  get '/turn_logs/:id', to: 'turn_logs#return_json'

  post '/landmark/', to: 'landmarks#create', as: 'create_landmark'

  resources :games do
    resources :chronicles do
      resources :turn_logs do
      end
    end
  end

  # get '/test3d', to: 'games#test3d'

  resources :games

  resources :board, only: [ :update , :show, :create]

  get '/create_board', to: 'board#create'

  get '/join/:game_slug', to: 'games#join_game'

  get '/play/:game_slug', to: "games#play_game", as: 'play_game'

  post '/players/:game_slug', to: "players#create", as: 'players'

  get '/tutorial', to: "tutorial#show", as: 'tutorial'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Cartogenesis
    %link{href: "http://fonts.googleapis.com/css?family=MedievalSharp", rel: "stylesheet", type: "text/css"}/
    %link{href: "http://fonts.googleapis.com/css?family=Amaranth", rel: "stylesheet", type: "text/css"}/
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #top_bar
      - if signed_in?
        = current_user.username
        = link_to "Sign out", signout_path, method: "delete"
        = link_to "New game", new_game_path, method: "get"
      - else
        = link_to "Sign in", new_user_path, method: "get"
      = yield
    / = button_to "Tutorial", tutorial_path, method: "get"

  / <div id="chat_window"></div>
  / <a href='#'><button id="start_chat">Start Chat!</button></a>
  /   <%= form_for '@task', url: {action: 'create'}, html: {class: "chat_form"} do |f| %>
  /   <p>
  /     <%= f.text_area :user_input, size: "60x3" %>
  /   </p>
  /   <p>
  /     <%= f.submit "Send" %>
  /   </p>
  / <% end %>